version: 2
before:
  hooks:
    - go mod download
    - go mod tidy
builds:
-
  id: awsdo-linux
  env:
    - CGO_ENABLED=0
  goos:
    - linux
  goarch:
    - amd64
    - arm64
  ldflags:
    - -s -w -X github.com/k1LoW/awsdo.version={{.Version}} -X github.com/k1LoW/awsdo.commit={{.FullCommit}} -X github.com/k1LoW/awsdo.date={{.Date}} -X github.com/k1LoW/awsdo/version.Version={{.Version}}
-
  id: awsdo-darwin
  env:
    - CGO_ENABLED=0
  goos:
    - darwin
  goarch:
    - amd64
    - arm64
  ldflags:
    - -s -w -X github.com/k1LoW/awsdo.version={{.Version}} -X github.com/k1LoW/awsdo.commit={{.FullCommit}} -X github.com/k1LoW/awsdo.date={{.Date}} -X github.com/k1LoW/awsdo/version.Version={{.Version}}
archives:
-
  id: awsdo-archive
  name_template: '{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  format_overrides:
    - goos: darwin
      format: zip
  files:
    - LICENSE
    - CREDITS
    - README.md
    - CHANGELOG.md
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
nfpms:
  -
    id: awsdo-nfpms
    file_name_template: "{{ .ProjectName }}_{{ .Version }}-1_{{ .Arch }}"
    builds:
    - awsdo-linux
    homepage: https://github.com/k1LoW/awsdo
    maintainer: Ken'ichiro Oyama <k1lowxb@gmail.com>
    description: awsdo is a tool to do anything using AWS temporary credentials.
    license: MIT
    formats:
      - deb
      - rpm
    bindir: /usr/bin
    epoch: 1
